"""Allow manual user ID insertion

Revision ID: 9f714c12bda3
Revises: 03f4034748fa
Create Date: 2025-08-23 03:49:07.908113

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = '9f714c12bda3'
down_revision: str | Sequence[str] | None = '03f4034748fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
